// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`
import { type Counter } from '@packages/counterdo';
interface CloudflareEnv {
  COUNTERS: DurableObjectNamespace<Counter>
}
