#:schema node_modules/wrangler/config-schema.json
name = "app"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "Counter"
script_name = "api"