name = "api"
compatibility_date = "2024-04-19"

[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "Counter"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]